const consoleEl = document.getElementById('console');
const statusIndicator = document.getElementById('status-indicator');
const loadBtn = document.getElementById('load-btn');
const clearBtn = document.getElementById('clear-btn');

let module = null;

function log(msg, type = '') {
  const now = new Date();
  const time = now.toTimeString().slice(0, 8);
  const line = document.createElement('div');
  line.className = 'console-line';
  line.innerHTML = `
    <span class="console-time">${time}</span>
    <span class="console-msg ${type}">${msg}</span>
  `;
  consoleEl.appendChild(line);
  consoleEl.scrollTop = consoleEl.scrollHeight;
}

function setStatus(status) {
  statusIndicator.className = `status-indicator ${status}`;
}

clearBtn.addEventListener('click', () => {
  consoleEl.innerHTML = '';
  log('Console cleared', 'info');
});

loadBtn.addEventListener('click', async () => {
  if (module) {
    log('Module already loaded', 'info');
    return;
  }
  
  consoleEl.innerHTML = '';
  log('Loading WebAssembly module...', 'info');
  setStatus('loading');
  loadBtn.disabled = true;
  
  try {
    // Dynamic import of the ES6 module generated by Emscripten
    const OrderEngineModule = await import('./order_engine.js');
    
    log('Initializing module...', 'info');
    
    // Create module instance with custom print handlers
    module = await OrderEngineModule.default({
      print: (text) => log(text),
      printErr: (text) => log(text, 'error'),
    });
    
    log('Module loaded successfully!', 'success');
    setStatus('ready');
    loadBtn.textContent = 'Module Loaded';
    
  } catch (err) {
    log(`Failed to load module: ${err.message}`, 'error');
    setStatus('error');
    loadBtn.disabled = false;
  }
});

